### ISSUE TITLE
ReindexJobs stuck in retry loop

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#768]
We're seeing an increasing number (66 right now) of ReindexJob tasks in Sidekiq all failling with the same exception:

```
ActiveRecord::RecordNotFound: Couldn't find Spotlight::FeaturedImage without an ID
```

Possibly related to #753.

It's for different exhibits and for uploaded resources:

![screen shot 2017-10-18 at 4 16 35 pm](https://user-images.githubusercontent.com/1861171/31747141-028efa34-b420-11e7-8597-a651e41fd852.png)
![screen shot 2017-10-18 at 4 20 19 pm](https://user-images.githubusercontent.com/1861171/31747183-4387bcc4-b420-11e7-9d40-4bf788e2e76e.png)

cc: @jkeck @cbeer @mejackreed

**Comment by mejackreed** [comment]
Looks like this has been happening for two weeks. My guess would be something here: 
https://github.com/sul-dlss/exhibits/pull/606 

more specifically: 
https://github.com/projectblacklight/spotlight/compare/v0.34.1...v1.0.0.alpha2

**Comment by drh-stanford** [comment]
thanks for the comment. i think i'm coming up against my limits of knowledge of spotlight internals to be super helpful debugging further. my best guess is the relaxation of the data relationships here -- https://github.com/projectblacklight/spotlight/commit/402bb7eebc497394bfc75d2c69038aba7ab3677c

the PR for that is a Rails upgrade -- https://github.com/projectblacklight/spotlight/pull/1813

**Comment by drh-stanford** [comment]
We've released v1.4.0 to production and we're still seeing this behavior of ReindexJobs not starting. Here's an example of a job stuck in the retries queue:

![screen shot 2017-10-19 at 4 40 02 pm](https://user-images.githubusercontent.com/1861171/31798990-2e877b1c-b4ec-11e7-912e-0b3ac60dbb5d.png)

**Comment by drh-stanford** [comment]
Also, I think we can rule out that it may be related to #753 as I tested that explicilty with the Travel through time exhibit in production. That data migration didn't solve this issue.

**Comment by drh-stanford** [comment]
Here's a full stack trace of the exception:

```
2017-10-20T15:54:38.390Z 50139 TID-1h7fvo Spotlight::ReindexJob JID-a4e7ce4d33e96bb61974c943 INFO: start
2017-10-20T15:54:39.107Z 50139 TID-1h7fvo Spotlight::ReindexJob JID-a4e7ce4d33e96bb61974c943 INFO: fail: 0.717 sec
2017-10-20T15:54:39.108Z 50139 TID-1h7fvo WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Spotlight::ReindexJob","queue":"default","args":[{"job_class":"Spotlight::ReindexJob","job_id":"0807a3c8-d8c8-4388-8391-02edfef4c1d2","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://exhibits/Spotlight::Exhibit/102"},{"_aj_globalid":"gid://exhibits/Spotlight::ReindexingLogEntry/394"}],"locale":"en"}],"retry":true,"jid":"a4e7ce4d33e96bb61974c943","created_at":1508514646.0684414,"enqueued_at":1508514878.3886313,"error_message":"Couldn't find Spotlight::FeaturedImage without an ID","error_class":"ActiveRecord::RecordNotFound","failed_at":1508514647.176919,"retry_count":3,"retried_at":1508514879.1063697},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"Spotlight::ReindexJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"Spotlight::ReindexJob\",\"job_id\":\"0807a3c8-d8c8-4388-8391-02edfef4c1d2\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://exhibits/Spotlight::Exhibit/102\"},{\"_aj_globalid\":\"gid://exhibits/Spotlight::ReindexingLogEntry/394\"}],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"a4e7ce4d33e96bb61974c943\",\"created_at\":1508514646.0684414,\"enqueued_at\":1508514878.3886313,\"error_message\":\"Couldn't find Spotlight::FeaturedImage without an ID\",\"error_class\":\"ActiveRecord::RecordNotFound\",\"failed_at\":1508514647.176919,\"retry_count\":2,\"retried_at\":1508514782.080873}"}
2017-10-20T15:54:39.108Z 50139 TID-1h7fvo WARN: ActiveRecord::RecordNotFound: Couldn't find Spotlight::FeaturedImage without an ID
2017-10-20T15:54:39.108Z 50139 TID-1h7fvo WARN: /opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/finder_methods.rb:66:in `find'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/querying.rb:3:in `find'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/core.rb:151:in `find'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/services/spotlight/carrierwave_file_resolver.rb:10:in `pattern'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/riiif-1.7.0/lib/riiif/abstract_file_system_resolver.rb:27:in `path'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/riiif-1.7.0/lib/riiif/abstract_file_system_resolver.rb:21:in `find'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/riiif-1.7.0/app/models/riiif/image.rb:49:in `file'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/riiif-1.7.0/app/models/riiif/image.rb:68:in `info'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/services/spotlight/upload_solr_document_builder.rb:23:in `add_image_dimensions'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/services/spotlight/upload_solr_document_builder.rb:9:in `block in to_solr'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/services/spotlight/upload_solr_document_builder.rb:7:in `tap'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/services/spotlight/upload_solr_document_builder.rb:7:in `to_solr'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/services/spotlight/solr_document_builder.rb:14:in `documents_to_index'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/jobs/spotlight/reindex_job.rb:12:in `block (2 levels) in <class:ReindexJob>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:59:in `block (2 levels) in find_each'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:59:in `each'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:59:in `block in find_each'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:121:in `block in find_in_batches'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:214:in `block in in_batches'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:198:in `loop'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:198:in `in_batches'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:120:in `find_in_batches'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/batches.rb:58:in `find_each'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/core_ext/enumerable.rb:43:in `each'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/core_ext/enumerable.rb:43:in `map'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/core_ext/enumerable.rb:43:in `sum'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/bundler/gems/spotlight-f5c3e65b204f/app/jobs/spotlight/reindex_job.rb:11:in `block in <class:ReindexJob>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:398:in `instance_exec'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:398:in `block in make_lambda'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:546:in `catch'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:546:in `block in default_terminator'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:170:in `block in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:454:in `block in call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:454:in `each'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:454:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_job.rb:46:in `perform'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `instance_exec'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:285:in `block in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:447:in `block in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/i18n-0.8.6/lib/i18n.rb:257:in `with_locale'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `instance_exec'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:285:in `block in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:447:in `block in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:164:in `instrument'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/logging.rb:44:in `block in tag_logger'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `tagged'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/logging.rb:44:in `tag_logger'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `instance_exec'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:285:in `block in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:447:in `block in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:90:in `run_callbacks'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/execution.rb:33:in `perform_now'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/execution.rb:22:in `block in execute'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:126:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/execution_wrapper.rb:85:in `wrap'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/reloader.rb:68:in `block in wrap'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/execution_wrapper.rb:81:in `wrap'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/reloader.rb:67:in `wrap'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `instance_exec'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:285:in `block in halting'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:447:in `block in around'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_execute_callbacks'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:90:in `run_callbacks'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/execution.rb:20:in `execute'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activejob-5.0.6/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:90:in `block in call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/execution_wrapper.rb:85:in `wrap'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:89:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/honeybadger-2.7.2/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by drh-stanford** [comment]
I've narrowed down the exception to here:

```
2.3.0 :005 > exhibit.resources[1]
 => #<Spotlight::Resources::Upload id: 4221, exhibit_id: 102, type: "Spotlight::Resources::Upload", url: nil, data: {"title"=>"Corpus Christi Logo", "spotlight_upload_description_tesim"=>"", "spotlight_upload_attribution_tesim"=>"", "date"=>""}, indexed_at: nil, created_at: "2017-08-10 20:14:05", updated_at: "2017-08-10 20:14:05", metadata: nil, index_status: nil, upload_id: nil> 
2.3.0 :007 > exhibit.resources[1].document_builder.documents_to_index
ActiveRecord::RecordNotFound: Couldn't find Spotlight::FeaturedImage without an ID
	from /opt/app/exhibits/exhibits/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
```

**Comment by drh-stanford** [comment]
It looks like there is a `migrate_to_iiif[hostname]` rake task that calls this function which copies the `upload_id` value into where it's missing above. 

https://github.com/projectblacklight/spotlight/blob/master/lib/migration/iiif.rb#L76

**Comment by drh-stanford** [comment]
I was successful in uploading an image to the Parker exhibit and it did populate the `upload_id` column in the Upload resource. So, it looks like there's another missing migration that we need to do to populate the `upload_id` columns to point to the new FeaturedImage structure.

**Comment by drh-stanford** [comment]
I was able to correct the Parker-2 exhibit and it's reindexing now in production. The correction (temporary) that I did was to  upload a test image, mark it private, and then link the broken `upload_id` to it. 

There's 94 of these broken upload images, so we need to remediate them and figure out a permanent fix.

**Comment by mejackreed** [comment]
Final piece of work is to remediate content in production.

**Comment by jkeck** [comment]
From Slack Thread:

**Comment by jkeck** [comment]
I have remediated the data in production.  There are no longer any `Upload` objects without an `upload_id`.

FWIW, there were only two exhibits that had not since been deleted that had the uploads associated with them.  In all cases the only trace of the upload was the database row itself (e.g. no file on the server and no solr document associated with that document present in the index).

The two exhibits that had uploads associated with them were https://exhibits.stanford.edu/medieval (not published) and https://exhibits.stanford.edu/blrcc (published).

We can try to reindex one or both of those exhibits first and validate via the job queue that they re-index cleanly before tackling #776.

**Comment by jkeck** [comment]
Closing this, if we end up still having problems re-indexing when working on #776 then we can re-open this.
