### ISSUE TITLE
Review dms mani's for the following druids

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#809]
#806 adds the ability to index SDR content annos from custom manifests. Some of these manifests are failing though in our parsing code. See:

 - `cy939pz1380`
 - `ng831fz5582`
 - `nh939rq0328`
 - `ky326yt7099`
 - `nf493zc0003`
 - `bv853hz1650 `

<details>
<summary>Errors look like this:</summary>

```
2017-11-01T15:10:34.988Z 30391 TID-oxbxtkoc4 WARN: NoMethodError: undefined method `has_key?' for "http://stacks.stanford.edu/image/nf493zc0003/156_iii_R_TC_46":String
2017-11-01T15:10:34.988Z 30391 TID-oxbxtkoc4 WARN: /Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:202:in `from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:212:in `block in from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `each'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:221:in `block (2 levels) in from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `each'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `block in from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `each'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:221:in `block (2 levels) in from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `each'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `block in from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `each'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:221:in `block (2 levels) in from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `each'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `block in from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `each'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `from_ordered_hash'
/Users//.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:50:in `parse'
/Users//dev/exhibits/app/models/iiif_manifest_harvester.rb:19:in `manifest'
/Users//dev/exhibits/app/models/iiif_manifest_harvester.rb:14:in `canvases'
/Users//dev/exhibits/app/models/iiif_canvas_indexer_enqueuer.rb:39:in `canvases'
/Users//dev/exhibits/app/models/iiif_canvas_indexer_enqueuer.rb:15:in `enqueue_jobs'
/Users//dev/exhibits/app/jobs/index_related_content_job.rb:4:in `perform'
```
</details>

**Comment by mejackreed** [comment]
Confirmed working now.
